# Generated by Django 2.1.2 on 2021-02-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appmodel',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
